---
- name: playbook
  hosts: "{{entorno}}"
  tasks:
    - name: Clonando repositorio git JLAC008 CrudBackend
      git:
        repo: "https://github.com/JLAC008/CrudBackend"
        dest: "/home/proyectos/JLAC008/CrudBackend"
        force: yes
        update: yes

    - name: Copiando la carpeta resources
      ansible.builtin.copy:
        src: ~/IdeaProjects/CrudBackend/CrudJLAC/src/main/resources/
        dest: /home/proyectos/JLAC008/CrudBackend/CrudJLAC/src/main/resources/

    - name: Crear red Docker llamada app-net
      community.docker.docker_network:
        name: app-net
        state: present
        driver: bridge

    - name: Run `docker-compose down` CrudBackend
      community.docker.docker_compose_v2:
        project_src: /home/proyectos/JLAC008/CrudBackend/CrudJLAC/docker
        state: absent
      register: output

    - name: Run `docker-compose up` CrudBackend
      community.docker.docker_compose_v2:
        project_src: /home/proyectos/JLAC008/CrudBackend/docker
        build: always
      register: output

    - name: Clonando repositorio git JLAC008 CrudFrontend
      git:
        repo: "https://github.com/JLAC008/CrudFrontend"
        dest: "/home/proyectos/JLAC008/CrudFrontend"
        force: yes
        update: yes

    - name: Run `docker-compose down` CrudFrontend
      community.docker.docker_compose_v2:
        project_src: /home/proyectos/JLAC008/CrudFrontend/docker
        state: absent
      register: output

    - name: Run `docker-compose up` CrudFrontend
      community.docker.docker_compose_v2:
        project_src: /home/proyectos/JLAC008/CrudFrontend/docker
        build: always
      register: output